blog/urls.py
from django.urls import path

from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.ArticleListView.as_view(), name='article_list'),
    path('<uuid:pk>/', views.ArticleDetailView.as_view(), name='article_detail'),
    path('create/', views.ArticleCreateView.as_view(), name='article_create'),
    path('<uuid:pk>/update/', views.ArticleUpdateView.as_view(), name='article_update'),
    path('<uuid:pk>/delete/', views.ArticleDeleteView.as_view(), name='article_delete'),
    path('search/', views.ArticleSearchListView.as_view(), name='article_search'),
    path('comment/<uuid:article_id>/', views.CommentCreate.as_view(), name='comment_create'),
    path('category/<slug:slug>/', views.CategoryListView.as_view(), name='category_list'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),

    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls')),

    path('blog/', include('blog.urls')),

    path('', include('pages.urls')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

blog/models.py
import uuid
from django.db import models
from django.contrib.auth import get_user_model
from django.utils import timezone
from django.urls import reverse
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db.models import Avg


class CommentManager(models.Manager):
    def active_comments(self):
        return self.filter(active=True)


class CategoryManager(models.Manager):
    def active_category(self):
        return self.filter(status=True)


class ArticleManager(models.Manager):
    def published(self):
        return self.filter(status='p')
    

class IPAddress(models.Model):
    ip_address = models.GenericIPAddressField()

    def __str__(self):
        return self.ip_address
    
    class Meta:
        verbose_name = 'آیپی آدرس'
        verbose_name_plural = 'آیپی آدرس ها'


class Category(models.Model):
    title = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255, unique=True)
    datetime_created = models.DateTimeField(auto_now_add=True)
    datetime_updated = models.DateTimeField(auto_now=True)
    status = models.BooleanField(default=True)

    objects = CategoryManager()

    def __str__(self) -> str:
        return self.title

    class Meta:
        verbose_name = 'دسته بندی'
        verbose_name_plural = 'دسته بندی ها'


class Article(models.Model):
    STATUS_CHOICES = (
        ('p', 'Published'),
        ('d', 'Draft'),
    )

    id = models.UUIDField(
        primary_key=True, default=uuid.uuid4, editable=False, db_index=True
    )
    title = models.CharField(max_length=255)
    description = models.TextField()
    author = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    cover = models.ImageField(upload_to='article/covers/')
    publish = models.DateTimeField(default=timezone.now)
    datetime_created = models.DateTimeField(auto_now_add=True)
    datetime_updated = models.DateTimeField(auto_now=True)
    category = models.ManyToManyField(Category, related_name='articles')
    hits = models.ManyToManyField(IPAddress, through='ArticleHit', blank=True, related_name='hits')
    status = models.CharField(max_length=1, choices=STATUS_CHOICES)

    objects = ArticleManager()

    class Meta:
        ordering = ['-publish']
        indexes = [
            models.Index(fields=['id'], name='id_index'),
            models.Index(fields=['publish'])
        ]
        verbose_name = 'مقاله'
        verbose_name_plural = 'مقالات'

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:article_detail', args=[str(self.id)])

    def get_category(self):
        return ', '.join(category.title for category in self.category.active_category())

    def category_active(self):
        return self.category.filter(status=True)

    def average_rate(self):
        comments = Comment.objects.filter(article=self).aggregate(average=Avg('rate'))
        avg = 0
        if comments['average'] is not None:
            avg = float(comments['average'])
        return avg


class Comment(models.Model):
    author = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    article = models.ForeignKey(
        Article, on_delete=models.CASCADE, related_name='comments')
    email = models.EmailField()
    text = models.TextField()
    rate = models.IntegerField(default=0, validators=[
                               MinValueValidator(0), MaxValueValidator(5)])
    active = models.BooleanField(default=True)
    datetime_created = models.DateTimeField(auto_now_add=True)
    datetime_updated = models.DateTimeField(auto_now=True)

    objects = CommentManager()

    def __str__(self) -> str:
        return f'{self.author} for {self.article}'

    class Meta:
        verbose_name = 'نظر '
        verbose_name_plural = 'نظرات'

    def get_absolute_url(self):
        return reverse('blog:article_detail', args=[str(self.article.id)])


class ArticleHit(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    ip_address = models.ForeignKey(IPAddress, on_delete=models.CASCADE)
    datetime_created = models.DateTimeField(auto_now_add=True)

blog/forms.py
from django import forms
from django.core.mail import send_mail

from .models import Article, Comment


class ArticleCreateForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = ['title', 'description', 'cover', 'publish', 'status', 'category']


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['email', 'text', 'rate']
        

blog/views.py
from django.shortcuts import render, get_object_or_404
from django.views import generic
from django.urls import reverse_lazy
from django.db.models import Q, Count

from .models import Article, Category
from .forms import ArticleCreateForm, CommentForm
from .tasks import comment_send_mail_reader, comment_send_mail_author


class ArticleListView(generic.ListView):
    queryset = Article.objects.published()
    template_name = 'blog/article_list.html'
    context_object_name = 'articles'


class CategoryListView(generic.ListView):
    template_name = 'blog/category_list.html'
    context_object_name = 'articles'

    def get_queryset(self):
        global category
        slug = self.kwargs.get('slug')
        category = get_object_or_404(
            Category.objects.active_category(), slug=slug,)
        return category.articles.published()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['category'] = category
        return context


class ArticleDetailView(generic.DetailView):
    template_name = 'blog/article_detail.html'
    context_object_name = 'article'

    def get_object(self):
        global article
        pk = self.kwargs.get('pk')
        article = get_object_or_404(Article.objects.published(), id=pk)

        ip_address = self.request.user.ip_address
        if ip_address not in article.hits.all():
            article.hits.add(ip_address)
        return article

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['comments'] = article.comments.active_comments()
        context['comment_form'] = CommentForm()
        tags = article.category_active().values_list('id', flat=True)
        similar_articles = Article.objects.published().filter(
            category__in=tags).exclude(id=article.id)
        similar_articles = similar_articles.annotate(
            same_tag=Count('category')).order_by('-same_tag', '-publish')[:4]
        context['similar_articles'] = similar_articles
        return context


class ArticleCreateView(generic.CreateView):
    form_class = ArticleCreateForm
    template_name = 'blog/article_create_update.html'

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class ArticleUpdateView(generic.UpdateView):
    model = Article
    form_class = ArticleCreateForm
    template_name = 'blog/article_create_update.html'


class ArticleDeleteView(generic.DeleteView):
    model = Article
    template_name = 'blog/article_delete.html'
    success_url = reverse_lazy('blog:article_list')


class ArticleSearchListView(generic.ListView):
    template_name = 'blog/article_search.html'
    context_object_name = 'articles'

    def get_queryset(self):
        q = self.request.GET.get('q')
        return Article.objects.filter(Q(title__icontains=q) | Q(description__icontains=q))

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['q'] = self.request.GET.get('q')
        return context


class CommentCreate(generic.CreateView):
    form_class = CommentForm

    def form_valid(self, form):
        article_id = self.kwargs.get('article_id')
        article = get_object_or_404(Article, id=article_id)
        form.instance.article = article
        form.instance.author = self.request.user
        # reader
        read_email = form.cleaned_data.get('email')
        username = self.request.user.username
        # author
        title = article.title
        author_email = article.author.email

        if self.request.user != article.author:
            comment_send_mail_reader.delay(username, read_email)
            comment_send_mail_author.delay(title, author_email, username)

        return super().form_valid(form)
    

blog/templates/blog/article_create_update.html
{% extends '_base.html' %}

{% load crispy_forms_tags %}

{% block title %}
    Create
{% endblock %}

{% block content %}
    <div class="heading-page header-text">
    </div>
    <section class="blog-posts grid-system mt-1">
        <div class="container">
            <div class="row">
                <div class="col-lg-8">
                    <div class="all-blog-posts">
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="sidebar-item submit-comment">
                                    <div class="sidebar-heading">
                                        <h2>Create Article</h2>
                                    </div>
                                    <div class="content">
                                        <form id="comment" action="" method="POST" enctype="multipart/form-data">
                                            {% csrf_token %}
                                            <div class="row">
                                                <div class="col-md-6 col-sm-12">
                                                    {{ form|crispy }}
                                                    <div class="col-lg-12">
                                                    <fieldset>
                                                        <button type="submit" id="form-submit" class="main-button">Submit</button>
                                                    </fieldset>
                                                  </div>
                                            </div>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

blog/templates/blog/article_detail.html
{% extends '_base.html' %}

{% load static %}
{% load crispy_forms_tags %}

{% block title %}
    Article Detail: {{ article.title }}
{% endblock %}

{% block custom_css %}
    <link rel="stylesheet" href="{% static 'assets/css/star.css' %}">
{% endblock %}

{% block content %}
<div class="heading-page header-text">
</div>
<section class="blog-posts grid-system">
    <div class="container">
        <div class="row">
            <div class="col-lg-8">
                <div class="all-blog-posts">
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="blog-post">
                                <div class="blog-thumb">
                                    <img src="{{ article.cover.url }}" alt>
                                </div>
                                <div class="down-content">
                                    <a href="post-details.html"><h4>{{ article.title }}</h4></a>
                                    <ul class="post-info">
                                        <li><a href="#">{{ article.author }}</a></li>
                                        <li>{{ article.publish }}</li>
                                        <li>
                                            <i class="far fa-star star two-star fas rate-active"></i>
                                            {{ article.average_rate|stringformat:'.2f' }}
                                        </li>
                                        <li>{{ article.hits.count }}</li>
                                        <li>{{ article.comments.count }} Comments</li>
                                    </ul>
                                    <p>
                                        {{ article.description|linebreaks }}
                                    </p>
                                    <div class="post-options">
                                        <div class="row">
                                            <div class="col-6">
                                                <ul class="post-tags">
                                                    <li><i class="fa fa-tags"></i></li>
                                                    {% for cat in article.category_active.all %}
                                                    <li><a
                                                            href="{% url 'blog:category_list' cat.slug %}">
                                                            {{ cat.title }}</a>,</li>
                                                    {% endfor %}
                                                </ul>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                          <div class="col-lg-12">
                            <div class="sidebar-item comments">
                              <div class="sidebar-heading">
                                <h2>{{ article.comments.count }}</h2>
                              </div>
                              <div class="content">
                                <ul>
                                    {% for comment in comments %}
                                        <li style="display: block;">
                                            <div class="author-thumb">
                                                <img src="{% static 'assets/images/comment-author-01.jpg' %}" style="margin-top: -20px;" alt="">
                                                </div>
                                                <div class="right-content">
                                                <h4>{{ comment.author }}<span>{{ comment.datetime_created }}</span></h4>
                                                <p>{{ comment.text }}</p>
                                                <i class="far fa-star star two-star {% if comment.rate >= 1 %} fas rate-active {% endif %}"></i>
                                                <i class="far fa-star star two-star {% if comment.rate >= 2 %} fas rate-active {% endif %}"></i>
                                                <i class="far fa-star star two-star {% if comment.rate >= 3 %} fas rate-active {% endif %}"></i>
                                                <i class="far fa-star star two-star {% if comment.rate >= 4 %} fas rate-active {% endif %}"></i>
                                                <i class="far fa-star star two-star {% if comment.rate >= 5 %} fas rate-active {% endif %}"></i>
                                            </div>
                                        </li>
                                    {% endfor %}
                                </ul>
                              </div>
                            </div>
                          </div>
                        <div class="col-lg-12">
                            <div class="sidebar-item submit-comment">
                                <div class="sidebar-heading">
                                    <h2>Your comment</h2>
                                </div>
                                <div class="content">
                                    <form id="comment"
                                        action="{% url 'blog:comment_create' article.pk %}"
                                        method="POST">
                                        {% csrf_token %}
                                        <div class="row">
                                            <div class="col-md-6 col-sm-12">
                                                <fieldset>
                                                    <input name="email"
                                                        type="email" id="email"
                                                        placeholder="Your email"
                                                        required>
                                                </fieldset>
                                            </div>
                                            <div class="col-lg-12">
                                                <fieldset>
                                                    <textarea name="text"
                                                        rows="6" id="message"
                                                        placeholder="Type your comment"
                                                        required></textarea>
                                                </fieldset>
                                            </div>
                                            <div class="col-lg-12 mt-5">
                                                <fieldset>
                                                    <button type="submit"
                                                        id="form-submit"
                                                        class="main-button">Submit</button>
                                                </fieldset>
                                            </div>
                                        </div>
                                        <div class="wrap">
                                            <div class="stars">
                                                <label class="rate">
                                                    <input type="radio" name="rate" id="star1" value="1">
                                                    <div class="face"></div>
                                                    <i class="far fa-star star one-star"></i>
                                                </label>
                                                <label class="rate">
                                                    <input type="radio" name="rate" id="star2" value="2">
                                                    <div class="face"></div>
                                                    <i class="far fa-star star two-star"></i>
                                                </label>
                                                <label class="rate">
                                                    <input type="radio" name="rate" id="star3" value="3">
                                                    <div class="face"></div>
                                                    <i class="far fa-star star three-star"></i>
                                                </label>
                                                <label class="rate">
                                                    <input type="radio" name="rate" id="star4" value="4">
                                                    <div class="face"></div>
                                                    <i class="far fa-star star four-star"></i>
                                                </label>
                                                <label class="rate">
                                                    <input type="radio" name="rate" id="star5" value="5">
                                                    <div class="face"></div>
                                                    <i class="far fa-star star five-star"></i>
                                                </label>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-4">
                <div class="sidebar">
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="sidebar-item recent-posts">
                                <div class="sidebar-heading">
                                    <h2>Similar Articles</h2>
                                </div>
                                {% for article in similar_articles %}
                                    <div class="content">
                                        <ul>
                                            <li>
                                                <a href="{% url 'blog:article_detail' article.pk %}">
                                                    <h5>{{ article.title }}</h5>
                                                    <span>{{ article.publish }}</span>
                                                </a>
                                            </li>
                                        </ul>
                                    </div>
                                    <br>
                                {% endfor %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

{% block custom_js %}
    <script src="{% static 'assets/js/star.js' %}"></script> 
{% endblock %}

blog/templates/blog/article_list.html
{% extends '_base.html' %}

{% load static %}
{% load blog_tags %}

{% block title %}
Article List
{% endblock %}

{% block custom_css %}
    <link rel="stylesheet" href="{% static 'assets/css/star.css' %}">
{% endblock %}

{% block content %}
  {% most_view_in_week %}
  <!-- Banner Ends Here -->
  <section class="call-to-action">
    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <div class="main-content rounded-4">
            <div class="row">
              <div class="col-lg-8">
                <h4>Movie News</h4>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
  <section class="blog-posts">
    <div class="container">
      <div class="row">
        <div class="col-lg-8">
          <div class="all-blog-posts">
            <div class="row">
              {% for article in articles %}
              <div class="col-lg-12">
                <div class="blog-post">
                  <div class="blog-thumb">
                    <img src="{{ article.cover.url }}" alt>
                  </div>
                  <div class="down-content">
                    <a href="{% url 'blog:article_detail' article.id %}"><h4>
                      {{ article.title }}</h4></a>
                    <ul class="post-info">
                      <li><a href="#">{{ article.author }}</a></li>
                      <li>{{ article.publish }}</li>
                      <li>
                          <i class="far fa-star star two-star fas rate-active"></i>
                          {{ article.average_rate|stringformat:'.2f' }}
                      </li>
                      <li>{{ article.hits.count }}</li>
                      <li>{{ article.comments.count }} Comments</li>
                    </ul>
                    <p>{{ article.description|truncatewords:50 }}</p>
                    <div class="post-options">
                      <div class="row">
                        <div class="col-6">
                          <ul class="post-tags">
                            <li><i class="fa fa-tags"></i></li>
                            {% for cat in article.category_active.all %}
                            <li><a href="{% url 'blog:category_list' cat.slug %}">
                              {{ cat.title }}</a>,</li>
                            {% endfor %}
                          </ul>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              {% endfor %}
            </div>
          </div>
        </div>
        <div class="col-lg-4">
          <div class="sidebar">
            <div class="row">
              <div class="col-lg-12">
                <div class="sidebar-item search">
                  <form id="search_form" name="gs" method="GET"
                    action="{% url 'blog:article_search' %}">
                    <input type="text" name="q" class="searchText"
                      placeholder="type to search..." autocomplete="on">
                  </form>
                </div>
              </div>
              {% hot_articles %}
              {% high_rating %}
            </div>
          </div>
        </div>
      </div>
    </div>
</section>
{% endblock %}

blog/templates/blog/article_search.html
{% extends '_base.html' %}

{% load static %}

{% block title %}
    Article Search
{% endblock %}

{% block content %}
    <h2>Article List</h2>

    {% for article in articles %}
        <a href="{{ article.get_absolute_url }}">
            <img src="{{ article.cover.url }}" alt="">
            <h3>{{ article.title }}</h3>
        </a>
        <p>{{ article.description|truncatewords:20 }}</p>
        <p>{{ article.author }}</p>
        <hr>
    {% endfor %}

    <form action="{% url 'blog:article_search' %}" method="GET">
        <input type="search" name="q">
    </form>

    <a href="{% url 'blog:article_list' %}">article list</a>

    <div class="main-banner header-text">
        <div class="container-fluid">
          <div class="owl-banner owl-carousel">
            <div class="item">
              <img src="{% static 'assets/images/banner-item-01.jpg' %}" alt>
              <div class="item-content">
                <div class="main-content">
                  <div class="meta-category">
                    <span>aaaaa</span>
                  </div>
                  <a href="post-details.html"><h4>aaaaaa</h4></a>
                  <ul class="post-info">
                    <li><a href="#">Admin</a></li>
                    <li><a href="#">May 12, 2020</a></li>
                    <li><a href="#">12 Comments</a></li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <!-- Banner Ends Here -->
      <section class="call-to-action">
        <div class="container">
          <div class="row">
            <div class="col-lg-12">
              <div class="main-content rounded-4">
                <div class="row">
                  <div class="col-lg-8">
                    <h4>Search: {{ q }}</h4>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
      <section class="blog-posts">
        <div class="container">
          <div class="row">
            <div class="col-lg-8">
              <div class="all-blog-posts">
                <div class="row">
                  {% for article in articles %}
                  <div class="col-lg-12">
                    <div class="blog-post">
                      <div class="blog-thumb">
                        <img src="{{ article.cover.url }}" alt>
                      </div>
                      <div class="down-content">
                        <a href="{% url 'blog:article_detail' article.id %}"><h4>
                          {{ article.title }}</h4></a>
                        <ul class="post-info">
                          <li><a href="#">{{ article.author }}</a></li>
                          <li>{{ article.publish }}</li>
                          <li>12 Comments</li>
                        </ul>
                        <p>{{ article.description|truncatewords:50 }}</p>
                        <div class="post-options">
                          <div class="row">
                            <div class="col-6">
                              <ul class="post-tags">
                                <li><i class="fa fa-tags"></i></li>
                                {% for cat in article.category_active.all %}
                                <li><a href="{% url 'blog:category_list' cat.slug %}">
                                  {{ cat.title }}</a>,</li>
                                {% endfor %}
                              </ul>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                  {% endfor %}
                </div>
              </div>
            </div>
            <div class="col-lg-4">
              <div class="sidebar">
                <div class="row">
                  <div class="col-lg-12">
                    <div class="sidebar-item search">
                      <form id="search_form" name="gs" method="GET"
                        action="{% url 'blog:article_search' %}">
                        <input type="text" name="q" class="searchText"
                          placeholder="type to search..." autocomplete="on">
                      </form>
                    </div>
                  </div>
                  <div class="col-lg-12">
                    <div class="sidebar-item recent-posts">
                      <div class="sidebar-heading">
                        <h2>Recent Posts</h2>
                      </div>
                      <div class="content">
                        <ul>
                          <li><a href="post-details.html">
                              <h5>Vestibulum id turpis porttitor sapien facilisis
                                scelerisque</h5>
                              <span>May 31, 2020</span>
                            </a></li>
                        </ul>
                      </div>
                    </div>
                  </div>
                  <div class="col-lg-12">
                    <div class="sidebar-item categories">
                      <div class="sidebar-heading">
                        <h2>Categories</h2>
                      </div>
                      <div class="content">
                        <ul>
                          <li><a href="#">- Nature Lifestyle</a></li>
                        </ul>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
    </section>
{% endblock %}