accounts/urls.py
from django.urls import path

from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.SignUpView.as_view(), name='signup'),
]

blog/urls.py
from django.urls import path

from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.ArticleListView.as_view(), name='article_list'),
    path('<uuid:pk>/', views.ArticleDetailView.as_view(), name='article_detail'),
    path('create/', views.ArticleCreateView.as_view(), name='article_create'),
    path('<uuid:pk>/update/', views.ArticleUpdateView.as_view(), name='article_update'),
    path('<uuid:pk>/delete/', views.ArticleDeleteView.as_view(), name='article_delete'),
    path('search/', views.ArticleSearchListView.as_view(), name='article_search'),
    path('comment/<uuid:article_id>/', views.CommentCreate.as_view(), name='comment_create'),
    path('category/<slug:slug>/', views.CategoryListView.as_view(), name='category_list'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),

    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls')),

    path('blog/', include('blog.urls')),

    path('', include('pages.urls')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

pages/urls.py
from django.urls import path

from . import views

app_name = 'pages'

urlpatterns = [
    path('', views.HomePageView.as_view(), name='home'),
]

templates/_base.html
{% load static %}

{% load blog_tags %}

<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="TemplateMo">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" 
    integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css">
    <link href="https://fonts.googleapis.com/css?family=Roboto:100,100i,300,300i,400,400i,500,500i,700,700i,900,900i&display=swap" rel="stylesheet">

    <title>{% block title %}{% endblock %}</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">


    <!-- Additional CSS Files -->
    <link rel="stylesheet" href="{% static 'assets/css/fontawesome.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/templatemo-stand-blog.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/owl.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/custom.css' %}">

    {% block custom_css %}
    {% endblock %}
<!--

TemplateMo 551 Stand Blog

https://templatemo.com/tm-551-stand-blog

-->
</head>

<body>

    <!-- ***** Preloader Start ***** -->
    <div id="preloader">
        <div class="jumper">
            <div></div>
            <div></div>
            <div></div>
        </div>
    </div>  
    <!-- ***** Preloader End ***** -->

    <!-- Header -->
    <header class="">
    <nav class="navbar navbar-expand-lg">
        <div class="container">
        <a class="navbar-brand" href="{% url 'pages:home' %}"><h2>My Weblog</h2></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'blog:article_list' %}">Blog</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'blog:article_create' %}"><i class="fa-solid fa-plus"></i> New Article</a>
            </li>
            {% category_navbar %}
            <div class="dropdown">
                <button class="btn btn-primary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    {% if user.is_authenticated %}
                        <i class="fa-solid fa-user"></i> Hello {{ user.username }}
                    {% else %}
                        <i class="fa-solid fa-user"></i> Hello guest
                    {% endif %}
                </button>
                <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                    {% if user.is_authenticated %}
                        <a class="dropdown-item" href="{% url 'logout' %}">Log out</a>
                        <a class="dropdown-item" href="{% url 'password_change' %}">Change Password</a>
                    {% else %}
                        <a class="dropdown-item" href="{% url 'login' %}">Log In</a>
                        <a class="dropdown-item" href="{% url 'accounts:signup' %}">Sign Up</a>
                    {% endif %}
                </div>
              </div>
            </ul>
        </div>
        </div>
    </nav>
    </header>

    {% block content %}
    {% endblock %}

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" 
    integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" 
    crossorigin="anonymous"></script>

    <footer>
        <div class="container">
        <div class="row">
            <div class="col-lg-12">
            <div class="copyright-text">
                <p>My Weblog                    
            </div>
            </div>
        </div>
        </div>
    </footer>

    <!-- Bootstrap core JavaScript -->
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

    <!-- Additional Scripts -->
    <script src="{% static 'assets/js/custom.js' %}"></script>
    <script src="{% static 'assets/js/owl.js' %}"></script>
    <script src="{% static 'assets/js/slick.js' %}"></script>
    <script src="{% static 'assets/js/isotope.js' %}"></script>
    <script src="{% static 'assets/js/accordions.js' %}"></script>

    {% block custom_js %}
    {% endblock %}

    <script language = "text/Javascript"> 
        cleared[0] = cleared[1] = cleared[2] = 0; //set a cleared flag for each field
        function clearField(t){                   //declaring the array outside of the
        if(! cleared[t.id]){                      // function makes it static and global
            cleared[t.id] = 1;  // you could use true and false, but that's more typing
            t.value='';         // with more chance of typos
            t.style.color='#fff';
            }
        }
    </script>

    </body>
</html>

templates/home.html
{% extends '_base.html' %}

{% block title %}
    Home
{% endblock %}

{% block content %}
    <div class="card text-center">
        <div class="card-body">
        <h5 class="card-title margin-top">Welcome to my weblog</h5>
        <p>If you don`t have account <a href="{% url 'accounts:signup' %}" class="text text-primary">click here</a> for sign up.</p>
        <p>For login <a href="{% url 'login' %}" class="text text-primary">click here</a>.</p>
        </div>
    </div>
{% endblock %}